# Applied Cryptography

## Hashing

* Long plain text to deterministic short bytes
  ** SHA256: result is a 256-bit (32byte number), MD5, SHA3-xxx
* Porperties
  ** Only based on the input
  ** Use all  the input
  ** Uniform distribution
  ** Distinctive (almost same data different results)
  ** Short (fixed) digest

### Application
* Message integrity
* Digital signature
* Password verification
* Proof of work
* Data identifier

### Variants
* Message Digest Algorithm
  ** Ronald Rivest publist: 1989-2008
  ** MD2 / MD3 / MD4 / MD5 / MD6

### Hash collisions
* Two different text have the same hash-value


### Usage / Implementation

[,console]
----
openssl sha512 <fname>
----

[,python]
----
from cryptography.hazmat.primitives import hashes

digest = hashes.Hash(hashes.SHA256())
digest.update(text)               # Bytes
digestBytes = digest.finalize()   # Bytes
----

### Example openssl

[,console]
----
#!/bin/bash

text="Short text for demonstration purposes."
hashHex="953e457f640f114c10edeffe676e582e4f67df27d217422949887f4869e32de8"

digestHex=`echo "${text}\c" | openssl sha256 | sed -e 's/^.*= *//'`
if [ "${hashHex}" = "${digestHex}" ];
then
    echo "True", "${digestHex}"
else
    echo "False", "${digestHex}"
fi

----

### Example Python
[,python]
----
#!/usr/bin/env python3
# (c) Applied Cryptography 2021b2 f.h.schippers@hva.nl (2020)

from cryptography.hazmat.primitives import hashes

text = b"Short text to demonstrate how hashing works."
hashHex = "953e457f640f114c10edeffe676e582e4f67df27d217422949887f4869e32de8"

digest = hashes.Hash(hashes.SHA256())
digest.update(text)             # Bytes
digestBytes = digest.finalize() # Bytes
digestHex = digestBytes.hex()

print(digestHex == hashHex, digestHex)
----

### summarizing
* Long plain text to deterministic short bytes
* MD5, SHA 2, SHA 3
* Use: openssl and python3 and others
* Application: Message integrity, Digital Signature





* Secure Hash Algorithm
  ** NSA SHA0-2 / Guido Bertoni ea. SHA 3
  ** SHA 0 / SHA 1
  ** SHA 2 (NIST (National Institute of Standards and Technology) / FIPS US patent (royalty-free) publication:2001
     *** SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224, SHA-512/256
  ** SHA 3 (NIST 2015) publication: 2008
     *** SHA3-224, SHA3-256, SHA-384, SHA-512



## Symmetric encryption
* One key for encryption and decryption
* Small block algorithm
* Chaining mode to encrypt/ decrypt lager blocks
* Properties are important



## Asymmetric encryption

RSA (Rivest Shamir Adleman 1977)

* Asymmetric: Private Key, Public Key
* Practical difficulty of factoring product of large primes
* RSA-2048 (means a 2048-bit (256 bytes) can be encrypted)
* Used for signing and key-exchange
* Based on Group Theory (x^Y^ mod n)

